maktek/Models/Model.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maktek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aksateknikEntities : DbContext
    {
        public aksateknikEntities()
            : base("name=aksateknikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kullanici> kullanici { get; set; }
    }
}

maktek/Models/Model.Designer.cs
// T4 code generation is enabled for model 'D:\web\maktek\maktek\maktek\Models\Model.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

maktek/Models/Model.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

maktek/Models/kullanici.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maktek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int Id { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ekleme_tarihi { get; set; }
        public string ekleyen_kul { get; set; }
        public Nullable<System.DateTime> degisim_tarihi { get; set; }
        public string degistiren_kul { get; set; }
        public string resim { get; set; }
    }
}

maktek/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maktek.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            ViewBag.title = "AKSA | Hakkımızda";
            return View();
        }
    }
}

maktek/Controllers/BlogAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maktek.Controllers
{
    public class BlogAdminController : Controller
    {
        // GET: BlogAdmin
        public ActionResult Index()
        {
            return View();
        }
    }
}

maktek/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maktek.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            ViewBag.Title = "Aksa | Haberler";
            return View();
        }

        public ActionResult Category()
        {
            return View();
        }

        public ActionResult Populer()
        {
            return View();
        }


        public ActionResult Tag()
        {
            return View();
        }

        public ActionResult Detail()
        {
            return View();
        }
    }
}

maktek/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maktek.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            ViewBag.Title = "Aksa Teknik | İletişim";
            return View();
        }
    }
}

maktek/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace maktek.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.title = "AKSA || İklimlendirme Uzmanı";
            return View();
        }
        public ActionResult Slider()
        {
            return View();
        }
        public ActionResult Info()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult Counter()
        {
            return View();
        }

        public ActionResult Blog()
        {
            ViewBag.title = "AKSA || HABERLER";
            return View();
        }
    }
}

maktek/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using maktek.Models;

namespace maktek.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login

        aksateknikEntities db = new aksateknikEntities();
        public ActionResult Index()
        {
            var model = db.kullanici.ToList();
            return View();
        }
    }
}

maktek/Views/About/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="inner-banner has-base-color-overlay text-center" style="background: url(/Content/site/images/background/1.jpg);">
    <div class="container">
        <div class="box">
            <h3>AKSA HAKKINDA</h3>
        </div><!-- /.box -->
    </div><!-- /.container -->
</div>
<div class="breadcumb-wrapper">
    <div class="container">
        <div class="pull-left">
            <ul class="list-inline link-list">
                <li>
                    <a href="@Url.Action("Index", "Home")">Ana Sayfa</a>
                </li>
                <!-- comment for inline hack
                -->
                <li>
                    Hakkımızda
                </li>
            </ul><!-- /.list-line -->
        </div><!-- /.pull-left -->
        <div class="pull-right">
            <a href="#" class="get-qoute"><i class="fa fa-share"></i>Paylaş</a>
        </div><!-- /.pull-right -->
    </div><!-- /.container -->
</div>
<section class="who-we-are-area padd-2">
    <div class="container">
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="who-we-are-img-holder">
                <img src="~/Content/site/images/resource/who.jpg" alt="Awesome Image" class="wow fadeIn animated" data-wow-duration="2s" data-wow-delay="0s" data-wow-offset="0" style="visibility: visible; animation-duration: 2s; animation-delay: 0s; animation-name: fadeIn;">
            </div>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
            <div class="content">
                <div class="sec-title style-2">
                    <h2>AKSA <span>kimdir</span></h2>
                </div>
                <div class="text">
                    Aksateknik 2000 yılında kurulmuş olup, kuruluşundan itibaren reformist ve müşteri memnuniyetini merkezine almış bir anlayışa sahip olmuştur.
                    <br> Müşterilerimizin taleplerini yerinde dinleyerek, kendilerine en uygun ve kalıcı çözümler konusunda rehberlik etmekteyiz. 
                </div>

                @* <div class="founder clearfix">
                    <div class="img-holder">
                        <img src="~/Content/site/images/resource/founder.jpg" alt="Awesome Image">
                    </div>
                    <div class="name">
                        <h3>Denial Muzad</h3>
                        <p>Founder &amp; CEO</p>
                    </div>
                </div>*@
                <div class="text">
                    Kalitemizi her daim yüksek tutarak, memnun ve mutlu bir müşteri portföyü oluşturmak önceliğimizdir.
                </div>
            </div>
        </div>
    </div>
</section>

maktek/Views/Blog/Category.cshtml
<div class="category-style-one sidebar-padd mar-1">
    <div class="inner-title">
        <h3>Kategoriler</h3>
    </div>
    <ul class="list">
        <li><a href="#" class="clearfix"><span class="float_left">Business Growth </span><span class="float_right">(8)</span></a></li>
        <li><a href="#" class="clearfix"><span class="float_left">Business Plans </span><span class="float_right">(3)</span></a></li>
        <li><a href="#" class="clearfix"><span class="float_left">Consulting </span><span class="float_right">(6)</span></a></li>
        <li><a href="#" class="clearfix"><span class="float_left">Funding Trends </span><span class="float_right">(9)</span></a></li>
        <li><a href="#" class="clearfix"><span class="float_left">Financial </span><span class="float_right">(7)</span></a></li>
    </ul>
</div> <!-- End of .sidebar_categories -->

maktek/Views/Blog/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="inner-banner has-base-color-overlay text-center" style="background: url(/content/site/images/background/1.jpg);">
    <div class="container">
        <div class="box">
            <h3>Haberin Devamı..</h3>
        </div><!-- /.box -->
    </div><!-- /.container -->
</div>

<div class="breadcumb-wrapper">
    <div class="container">
        <div class="pull-left">
            <ul class="list-inline link-list">
                <li>
                    <a href="@Url.Action("Index", "Home")">Ana Sayfa</a>
                </li>
                <li>
                    <a href="#">Haberler</a>
                </li>
                <li>
                    Haber Detayı
                </li>
            </ul><!-- /.list-line -->
        </div><!-- /.pull-left -->
        <div class="pull-right">
            <a href="#" class="get-qoute"><i class="fa fa-share"></i>share</a>
        </div><!-- /.pull-right -->
    </div><!-- /.container -->
</div>

<div class="sidebar-page-container">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <section class="blog-section padd-2">
                    <div class="large-blog-news single-blog-post single-blog wow fadeInUp animated animated" style="visibility: visible; animation-name: fadeInUp;">
                        <div class="img-box">
                            <img src="~/content/site/images/blog/bs.jpg" alt="News">
                        </div>
                        <div class="lower-content">
                            <div class="post-meta">By admin  /  March 12, 2018  /  03 Comments</div>
                            <h4><a href="blog-details.html">Get a credit online with our team’s professional help business strategy of the process.</a></h4>

                            <div class="text">
                                Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus. Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus. Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus.
                            </div>
                        </div><br>
                        <blockquote>Donec sollicitudin molestie erat sit amet elementum. Donec at lacinia massa, eu hen rit ex. Donec hendrerit, porttitor.Donec sollicitudin molestie erat sit amet elementum. Donec at lacinia massa, eu hen rit ex. Donec hendrerit, porttitor.</blockquote><br>
                        <div class="text">
                            <p>
                                Finibus ante et, imperdiet finibus risus. Donec malesuada luctus elit nec hendrerit. Integer ex sap ien, eleifend sit amet tellus ut, porttitor dictum velit. Nulla scelerisque, nisl eu maximus bibendum nibh risus eleifend ex, id dapibus leo dui in nulla.
                                Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus. <br><br>Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus. Lorem ipsum dolor sit amet, vix an natum labitur eleifend, mel amet a laorit menandri. Ei justo complectitur duo. Ei mundi solet ut soletu mel possit quo. Sea cu justo laudem. An utinam consulatu eos, est facilis suscipiantur te, vim te iudico delenit voluptatibus.
                            </p>
                        </div>
                    </div>
                    <div class="share-box clearfix">
                        <ul class="tag-box pull-left">
                            <li>Tags:</li>
                            <li><a href="#">Business,</a></li>
                            <li><a href="#">Finance,</a></li>
                            <li><a href="#">Consulting,</a></li>
                            <li><a href="#">Funding,</a></li>
                        </ul>
                        <div class="social-box pull-right">
                            <span>Share <i class="fa fa-share"></i></span>
                            <ul class="list-inline social">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>


                   



                    <div class="add_your_review">
                        <div class="inner-title">
                            <h3>Leave a comment</h3>
                        </div>
                       
                    </div>

                </section>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="blog-sidebar padd-4">


                    @Html.Action("Category", "Blog")
                    @Html.Action("Populer", "Blog")

                    @Html.Action("Tag", "Blog")
                 
                    <br>
                    <br>
                </div> <!-- End of .wrapper -->
            </div>
        </div>
    </div>
</div>

maktek/Views/Blog/Populer.cshtml
<div class="popular_news sidebar-padd mar-1">
    <div class="inner-title">
        <h3>En son haberler</h3>
    </div>

    <div class="popular-post">
        <div class="item">
            <div class="post-thumb"><a href="#"><img src="~/content/site/images/blog/1.jpg" alt=""></a></div>
            <h4><a href="#">Credit Suisse CEO focuses on wealth manageme...</a></h4>
            <div class="post-info">March 21, 2018 </div>
        </div>
        <div class="item">
            <div class="post-thumb"><a href="#"><img src="~/content/site/images/blog/2.jpg" alt=""></a></div>
            <h4><a href="#">Easy way to high global sotck marketin...</a></h4>
            <div class="post-info">March 21, 2018</div>
        </div>
        <div class="item">
            <div class="post-thumb"><a href="#"><img src="~/content/site/images/blog/3.jpg" alt=""></a></div>
            <h4><a href="#">Get a credit online with our team’s hel....</a></h4>
            <div class="post-info">March 21, 2018</div>
        </div>
    </div>
</div>

maktek/Views/Home/About.cshtml
<!--About Style One-->
<section class="about-style-one">
    <div class="outer-box clearfix">

        <!--Content Column-->
        <div class="content-column clearfix">
            <div class="content-box">
                <div class="inner-box wow fadeInLeft" data-wow-delay="0ms" data-wow-duration="1500ms">
                    <!--Section Title-->
                    <div class="sec-title">
                        <h2>AKSA <span>Hakkında</span></h2>
                    </div>
                    <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elitsed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo do consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla paria tur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum </div>
                    <div class="link-btn"><a href="@Url.Action("Index", "About")" class="btn-style-two">Okumaya Devam__ <span class="fa fa-long-arrow-right"></span></a></div>
                </div>
            </div>
        </div>

        <!--Image Column-->
        <div class="image-column" style="background-image: url(~/Content/site/images/resource/about.jpg);"><div class="image"><img src="~/Content/site/images/resource/about.jpg" alt=""></div><a href="https://www.youtube.com/watch?v=G0dzLanYW1E" class="overlay-link video-fancybox"><span class="icon fa fa-play"></span></a></div>
        
    </div>
</section>

maktek/Views/Home/Info.cshtml
<section class="call-to-action bg-1 padd-1">
    <div class="container">
        <div class="row clearfix">
            <!--Icon Column-->
            <div class="column icon-column col-md-4 col-sm-6 col-xs-12">
                <div class="inner-box">
                    <div class="icon"><span class="flaticon-technology"></span></div>
                    <h3>GSM:  +90 555-988-1757</h3>
                    <div class="text">1010 Berkler ave, Brooklyn, New York City, NY 10018 US</div>
                </div>
            </div>
            <!--Icon Column-->
            <div class="column icon-column col-md-4 col-sm-6 col-xs-12">
                <div class="inner-box">
                    <div class="icon"><span class="flaticon-circular-clock-tool"></span></div>
                    <h3>Çalışma Saatleri</h3>
                    <div class="text">Pazartesi - Cumartesi 08:00  - 19:00  / Pazar Kapalı</div>
                </div>
            </div>

            <!--Link Column-->
            <div class="column link-column col-md-4 col-sm-6 col-xs-12">
                <div class="link-btn5">
                    <a href="@Url.Action("Index", "Contact")" class="btn-style-two">İLETİŞİM</a>
                </div>
            </div>

        </div>
    </div>
</section>

<!--Services Two-->
<section class="services-two bg-1 padd-3">
    <div class="container">
        <div class="row clearfix">

            <!--Default Service Block-->
            <div class="default-service-block active col-md-4 col-sm-6 col-xs-12">
                <div class="inner-box">
                    <div class="icon"><span class="flaticon-graphic-3"></span></div>
                    <h3><a href="#">Business Growth</a></h3>
                    <div class="text">Consectetur adipiscing elit. Curabitur libero enim, lacinia finibus ante et, imperdiet finibus risus.</div>

                    <div class="link-btn">
                        <a href="#" class="btn-style-three dark">Read More</a>
                    </div>
                </div>
            </div>


            <!--Default Service Block / Active-->
            <div class="default-service-block active col-md-4 col-sm-6 col-xs-12">
                <div class="inner-box wow zoomIn" data-wow-delay="0ms" data-wow-duration="1500ms">
                    <div class="icon"><span class="flaticon-people"></span></div>
                    <h3><a href="#">24 Hours Online Support</a></h3>
                    <div class="text">Consectetur adipiscing elit. Curabitur libero enim, lacinia finibus ante et, imperdiet finibus risus.</div>
                    <div class="link-btn">
                        <a href="#" class="btn-style-three dark">Read More</a>
                    </div>
                </div>
            </div>

            <!--Default Service Block-->
            <div class="default-service-block active col-md-4 col-sm-6 col-xs-12">
                <div class="inner-box">
                    <div class="icon"><span class="flaticon-layers"></span></div>
                    <h3><a href="#">Business Strategy</a></h3>
                    <div class="text">Consectetur adipiscing elit. Curabitur libero enim, lacinia finibus ante et, imperdiet finibus risus.</div>
                    <div class="link-btn">
                        <a href="#" class="btn-style-three dark">Read More</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

maktek/Views/Home/Slider.cshtml
<!--Start rev slider wrapper-->
<section class="rev_slider_wrapper">
    <div id="slider1" class="rev_slider" data-version="5.0">
        <ul>
            <li data-transition="slotzoom-horizontal">
                <img src="@Url.Content("~/Content/site/images/slider/4.jpg")" alt="" width="1920" height="700" data-bgposition="top center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="1">

                <div class="tp-caption  tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="170"
                     data-transform_idle="o:1;"
                     data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0.01;s:3000;e:Power3.easeOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-mask_in="x:[100%];y:0;s:inherit;e:inherit;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="700">
                    <div class="slide-content-box">
                        <h1>İşyerinizin konforu için <br>çalışıyoruz.</h1>
                        <p>20 yılı aşkın tecrübemiz ile kapsamlı çözümler  <br>bulmanıza yardımcı oluyoruz. </p>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2300">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-five" href="@Url.Action("Index", "About")">HAKKIMIZDA</a>
                        </div>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="225"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2600">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-six" href="@Url.Action("Index", "Contact")">İLETİŞİM</a>
                        </div>
                    </div>
                </div>
            </li>
            <li data-transition="slotzoom-horizontal">
                <img src="@Url.Content("~/Content/site/images/slider/5.jpg")" alt="" width="1920" height="700" data-bgposition="top center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="1">

                <div class="tp-caption  tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="170"
                     data-transform_idle="o:1;"
                     data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0.01;s:3000;e:Power3.easeOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-mask_in="x:[100%];y:0;s:inherit;e:inherit;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="700">
                    <div class="slide-content-box">
                        <h1>We help businesses <br>innovate and grow.</h1>
                        <p>With over 10 years of experience helping businesses to find <br> comprehensive solutions. </p>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2300">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-five" href="@Url.Action("Index", "About")">HAKKIMIZDA</a>
                        </div>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="225"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2600">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-six" href="@Url.Action("Index", "Contact")">İLETİŞİM</a>
                        </div>
                    </div>
                </div>
            </li>
            <li data-transition="slotzoom-horizontal">
                <img src="@Url.Content("~/Content/site/images/slider/3.jpg")" alt="" width="1920" height="700" data-bgposition="top center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="1">

                <div class="tp-caption  tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="170"
                     data-transform_idle="o:1;"
                     data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0.01;s:3000;e:Power3.easeOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-mask_in="x:[100%];y:0;s:inherit;e:inherit;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="700">
                    <div class="slide-content-box">
                        <h1>We help businesses <br>innovate and grow.</h1>
                        <p>With over 10 years of experience helping businesses to find <br> comprehensive solutions. </p>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="15"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2300">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-five" href="@Url.Action("Index", "About")">HAKKIMIZDA</a>
                        </div>
                    </div>
                </div>
                <div class="tp-caption tp-resizeme"
                     data-x="left" data-hoffset="225"
                     data-y="top" data-voffset="410"
                     data-transform_idle="o:1;"
                     data-transform_in="y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;s:2000;e:Power4.easeInOut;"
                     data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;"
                     data-splitin="none"
                     data-splitout="none"
                     data-responsive_offset="on"
                     data-start="2600">
                    <div class="slide-content-box">
                        <div class="button">
                            <a class="btn-style-six" href="@Url.Action("Index", "Contact")">İLETİŞİM</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</section>
<!--End rev slider wrapper-->